# AUTHOR: Calvin Pan
# DATE CREATED: 1 June 2026
# DATE LAST MODIFIED: 23 June 2026
# PURPOSE: Convert the data generated by the Booking.com extension from JSON
# to a csv. Scans every participant export folder in analyse/inputs/, merges
# any that haven't been merged yet, converts each participant's events to
# rows, and concatenates everyone into a single csv.
# OUTPUTS: extension_converted.csv.
#   A csv file with the same information as the original JSONs (one
#   participant's events per row), in a more structured format. Each row is
#   tagged with `participant_code` so the combined file can be split back
#   apart downstream.

import json
import csv
from pathlib import Path
from datetime import datetime

# ---------------------------------------------------------------------------
# Raw extension export folders (e.g. inputs/qq9zdg2k/cell01_*.json, ...)
# The extension sometimes drops a folder named after the participant ID,
# containing one JSON (+ HTML) per cell instead of a single session export.
# Detect these and offer to merge them into one flat JSON in inputs/ so they
# can be picked up like any other session file below.
# ---------------------------------------------------------------------------

def find_export_folders(inputs_dir: Path) -> list:
    """Subdirectories of inputs_dir that directly contain one or more JSON files.

    Excludes inputs/merged/ itself, which holds this script's own output
    rather than a raw per-cell export from the extension.
    """
    return sorted(
        sub for sub in inputs_dir.iterdir()
        if sub.is_dir() and sub.name != "merged" and any(sub.glob("*.json"))
    )


def merge_export_folder(folder: Path, merged_dir: Path) -> Path:
    """
    Merge all per-cell JSON exports inside `folder` into a single JSON with
    the same top-level shape as a normal session export (participant/events),
    written to `merged_dir` (inputs/merged/), so 00a's conversion loop below
    can treat it like any other session file. Each event is tagged with its
    originating cell's metadata (_cellIndex, _cityKey, _checkin, _listIndex,
    _thumb).
    """
    json_files = sorted(folder.glob("*.json"))
    merged_events = []
    participant = None
    extension_version = None
    exported_at = None

    for jf in json_files:
        with open(jf, encoding="utf-8") as f:
            data = json.load(f)
        if participant is None:
            participant = data.get("participant")
        extension_version = data.get("extensionVersion", extension_version)
        exported_at = max(exported_at or "", data.get("exportedAt", "") or "")

        cell = data.get("cell", {})
        for event in data.get("events", []):
            merged_events.append({
                **event,
                "_cellIndex": cell.get("cellIndex"),
                "_cityKey": cell.get("cityKey"),
                "_checkin": cell.get("checkin"),
                "_listIndex": cell.get("listIndex"),
                "_thumb": cell.get("thumb"),
            })

    merged_events.sort(key=lambda e: e["timestamp"])

    merged = {
        "extensionVersion": extension_version,
        "exportedAt": exported_at,
        "participant": participant,
        "eventCount": len(merged_events),
        "events": merged_events,
    }

    subject_id = (participant or {}).get("subjectId") or folder.name
    out_path = merged_dir / f"{subject_id}_merged.json"
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(merged, f, ensure_ascii=False, indent=2)

    print(f"  → Merged {len(json_files)} files ({len(merged_events)} events) into {out_path.name}")
    return out_path


def merge_all_folders(inputs_dir: Path, merged_dir: Path) -> None:
    """
    Non-interactive version of the old prompt-per-folder flow: merge every
    export folder that doesn't already have a `<subjectId>_merged.json` in
    merged_dir, so the loop below always has a flat JSON to read per folder.
    """
    for folder in find_export_folders(inputs_dir):
        already_merged = list(merged_dir.glob(f"*{folder.name}*merged*.json"))
        if already_merged:
            continue
        n_json = len(list(folder.glob("*.json")))
        print(f"Dossier détecté : {folder.name}/ ({n_json} fichiers JSON) — fusion en cours...")
        merge_export_folder(folder, merged_dir)


# ---------------------------------------------------------------------------
# Discover every participant export folder in inputs/, merge the new ones
# into inputs/merged/, and load each one's events for conversion below.
# ---------------------------------------------------------------------------

inputs_dir = Path(__file__).parent.parent / "inputs"
inputs_dir.mkdir(parents=True, exist_ok=True)
merged_dir = inputs_dir / "merged"
merged_dir.mkdir(parents=True, exist_ok=True)
merge_all_folders(inputs_dir, merged_dir)

OUTPUT_DIR  = Path(__file__).parent.parent / "outputs"
OUTPUT_FILE = OUTPUT_DIR / "extension_converted.csv"

sessions = []  # list of (subject_id, events) — one per export folder
for folder in find_export_folders(inputs_dir):
    merged_candidates = list(merged_dir.glob(f"*{folder.name}*merged*.json"))
    if not merged_candidates:
        print(f"  ! Pas de fichier fusionné trouvé pour {folder.name}/, dossier ignoré.")
        continue
    merged_path = merged_candidates[0]

    with open(merged_path, encoding="utf-8") as f:
        raw = json.load(f)

    subject_id = (raw.get("participant") or {}).get("subjectId") or folder.name
    events = raw["events"]

    # ------------------------------------------------------------------
    # PART A: Drop scraped_content events — they do NOT correspond to real
    # user interactions, they are DOM snapshots of whatever cards were
    # present at a given moment.
    # ------------------------------------------------------------------
    events = [e for e in events if e["type"] != "scraped_content"]

    # ------------------------------------------------------------------
    # PART B: Sort events by timestamp (the JSON order is NOT
    # chronological — scraped_content events are flushed separately and
    # land first in the array regardless of when they occurred relative
    # to clicks/scrolls/hovers).
    # ------------------------------------------------------------------
    events.sort(key=lambda e: e["timestamp"])

    sessions.append((subject_id, events))

if not sessions:
    raise SystemExit(f"No export folders found in {inputs_dir}.")

# ---------------------------------------------------------------------------
# PART C: Convert to rows and save as CSV
# ---------------------------------------------------------------------------

def event_to_row(event: dict) -> dict:
    """
    Flatten one event dict into a CSV row.

    Common columns (present on almost every event type):
        type, timestamp, url, isTargetSample
        — tab_focus is the exception: its url can be null and it has no isTargetSample.

    Type-specific columns (None when not applicable):

    page_view
        referrer

    page_ready
        setupMs         — ms from navigation start to ready anchor (loading cost)
        afterPreload    — whether the preload loop ran before this anchor

    click
        kind            — InteractionKind (product_card / thumb_cue / sort_by /
                          reserve / more_info / other)
        targetTestId    — data-testid of the clicked element
        targetPropertyId
        targetText      — raw text content (newlines collapsed)
        metadata        — JSON-encoded dict (e.g. sort value for sort_by clicks)

    hover
        kind            — InteractionKind (never 'other')
        targetTestId
        targetPropertyId
        durationMs      — dwell duration, ms (cursor enter → exit), native on the event

    scroll
        scrollDepthPercent
        visiblePropertyIds  — JSON-encoded list

    viewport  (E8)
        targetPropertyId
        ratio           — intersectionRatio at threshold crossing
        isIntersecting

    visibility  (E11)
        state           — 'visible' | 'hidden'
        source          — 'visibilitychange' | 'focus' | 'blur' | 'init'

    tab_focus  (E11 cross-tab)
        tab_event       — 'activated' | 'window-focus' | 'window-blur'
        tabId
        windowId
        (url may be null; isTargetSample absent by design — service worker scope)

    filter_change
        kind            — 'price_filter'
        values          — JSON-encoded dict of aria-label → value

    pouce_explanation
        durationMs      — how long the tooltip stayed open (ms); null if session ended first
        trigger         — 'hover' | 'focus' | 'click' | 'unknown'
        targetPropertyId

    reserve  (E10)
        targetPropertyId
        displayedPrice  — raw price text shown at click time
        selectedRooms   — total rooms selected (-1 if selector miss)
        cellIndex       — position in design matrix (COMPLETED_NB index)

    health  (E12)
        page            — 'search' | 'detail' | 'other'
        failures        — JSON-encoded list of failed check names
        checks          — JSON-encoded list of {name, found, required}
        ok

    manip_check  (E4)
        thumb           — 'A' (absent) | 'P' (present) — expected treatment
        visiblePouceCount
        totalPouceCount
        shownCardCount
        ok

    cell_* columns (present on EVERY event, regardless of type)
        Injected by merge_export_folder() onto every event of a per-cell
        export folder (_cellIndex/_cityKey/_checkin/_listIndex/_thumb) — the
        cell/weekend an event belongs to is known unambiguously from which
        per-cell JSON file it came from, independent of the event's own
        schema. Without this, only `reserve` (native cellIndex) and
        `manip_check` (native thumb) carried any cell identity, leaving every
        other event type (viewport, click, hover, scroll, page_view, ...)
        impossible to attribute to a specific weekend downstream.
    """
    t = event["type"]

    # tab_focus has no isTargetSample and url can be null
    url             = event.get("url")
    is_target       = event.get("isTargetSample")

    row = {
        # --- always present ---
        "type":             t,
        "timestamp":        event["timestamp"],
        "url":              url,
        "isTargetSample":   is_target,

        # --- cell/weekend identity (merge-injected, every event) ---
        "cell_index":       event.get("_cellIndex"),
        "cell_city_key":    event.get("_cityKey"),
        "cell_checkin":     event.get("_checkin"),
        "cell_list_index":  event.get("_listIndex"),
        "cell_thumb":       event.get("_thumb"),

        # --- page_view ---
        "referrer":         event.get("referrer"),

        # --- page_ready ---
        "setupMs":          event.get("setupMs"),
        "afterPreload":     event.get("afterPreload"),

        # --- scroll ---
        "scrollDepthPercent": event.get("scrollDepthPercent"),
        "visiblePropertyIds": (
            json.dumps(event["visiblePropertyIds"], ensure_ascii=False)
            if "visiblePropertyIds" in event else None
        ),

        # --- click / hover / filter_change ---
        "kind":             event.get("kind"),

        # --- click / hover / viewport / pouce_explanation / reserve ---
        "targetTestId":     event.get("targetTestId"),
        "targetPropertyId": event.get("targetPropertyId"),

        # --- click ---
        # Collapse newlines/tabs and strip leading/trailing whitespace so that
        # targetText (which can capture raw script-tag content for kind="other"
        # clicks) doesn't bleed across CSV rows or become unreadable.
        "targetText":       " ".join((event.get("targetText") or "").split()) or None,
        "metadata":         (
            json.dumps(event["metadata"], ensure_ascii=False)
            if event.get("metadata") else None
        ),

        # --- hover / pouce_explanation ---
        # durationMs is emitted natively by the extension (cursor enter → exit for hover;
        # tooltip open duration for pouce_explanation). Null if the event was still open
        # when the session flushed.
        "durationMs":       event.get("durationMs"),

        # --- viewport (E8) ---
        "ratio":            event.get("ratio"),
        "isIntersecting":   event.get("isIntersecting"),

        # --- visibility (E11) ---
        "state":            event.get("state"),
        "source":           event.get("source"),

        # --- tab_focus (E11 cross-tab) ---
        # The field on the event is called 'event' — renamed to tab_event to avoid
        # collision with the 'type' concept.
        "tab_event":        event.get("event"),
        "tabId":            event.get("tabId"),
        "windowId":         event.get("windowId"),

        # --- filter_change ---
        "values":           (
            json.dumps(event["values"], ensure_ascii=False)
            if "values" in event else None
        ),

        # --- pouce_explanation ---
        "trigger":          event.get("trigger"),

        # --- reserve (E10) ---
        "displayedPrice":   event.get("displayedPrice"),
        "selectedRooms":    event.get("selectedRooms"),
        "cellIndex":        event.get("cellIndex"),

        # --- health (E12) ---
        "page":             event.get("page"),
        "failures":         (
            json.dumps(event["failures"], ensure_ascii=False)
            if "failures" in event else None
        ),
        "checks":           (
            json.dumps(event["checks"], ensure_ascii=False)
            if "checks" in event else None
        ),
        "ok":               event.get("ok"),

        # --- manip_check (E4) ---
        "thumb":            event.get("thumb"),
        "visiblePouceCount": event.get("visiblePouceCount"),
        "totalPouceCount":  event.get("totalPouceCount"),
        "shownCardCount":   event.get("shownCardCount"),
    }
    return row


# ---------------------------------------------------------------------------
# PART D: Convert timestamps (relative to each participant's OWN first event —
# t0 is per-session, not global, so "elapsed" still means time-since-start-
# of-that-subject's-session once everyone is concatenated together).
# ---------------------------------------------------------------------------

def format_timestamp(ts_ms: int, t0_ms: int) -> tuple:
    """
    Returns (datetime_local, elapsed_str) for a Unix timestamp in milliseconds.
      - datetime_local : local time as "YYYY-MM-DD HH:MM:SS.mmm"
      - elapsed_str    : time since start of session as "MM:SS.mmm"
    """
    dt = datetime.fromtimestamp(ts_ms / 1000)
    datetime_local = dt.strftime("%Y-%m-%d %H:%M:%S.") + f"{dt.microsecond // 1000:03d}"

    elapsed_ms = ts_ms - t0_ms
    minutes, remainder_ms = divmod(elapsed_ms, 60_000)
    seconds, ms = divmod(remainder_ms, 1000)
    elapsed_str = f"{int(minutes):02d}:{int(seconds):02d}.{int(ms):03d}"

    return datetime_local, elapsed_str


# Build all rows, one session (= one participant export folder) at a time
rows = []
for subject_id, events in sessions:
    if not events:
        continue
    t0_ms = events[0]["timestamp"]  # start of THIS participant's session
    for event in events:
        row = event_to_row(event)
        row["participant_code"] = subject_id
        row["datetime_local"], row["elapsed"] = format_timestamp(event["timestamp"], t0_ms)
        rows.append(row)

# Determine column order: fixed set so the CSV is always predictable
COLUMNS = [
    # identity
    "participant_code",
    # timing
    "timestamp",
    "datetime_local",
    "elapsed",
    # identity
    "type",
    "url",
    "isTargetSample",
    # cell/weekend identity (every event, see event_to_row docstring)
    "cell_index",
    "cell_city_key",
    "cell_checkin",
    "cell_list_index",
    "cell_thumb",
    # shared interaction fields
    "targetPropertyId",
    "kind",
    "durationMs",
    # page_view
    "referrer",
    # page_ready
    "setupMs",
    "afterPreload",
    # click / hover
    "targetTestId",
    "targetText",
    "metadata",
    # scroll
    "scrollDepthPercent",
    "visiblePropertyIds",
    # viewport (E8)
    "ratio",
    "isIntersecting",
    # visibility (E11)
    "state",
    "source",
    # tab_focus (E11 cross-tab)
    "tab_event",
    "tabId",
    "windowId",
    # filter_change
    "values",
    # pouce_explanation
    "trigger",
    # reserve (E10)
    "displayedPrice",
    "selectedRooms",
    "cellIndex",
    # health (E12)
    "page",
    "failures",
    "checks",
    "ok",
    # manip_check (E4)
    "thumb",
    "visiblePouceCount",
    "totalPouceCount",
    "shownCardCount",
]

# Also pick up any unexpected keys that might appear in future extension versions
extra_keys = sorted(
    {k for row in rows for k in row if k not in COLUMNS}
)
all_columns = COLUMNS + extra_keys

# Save the CSV
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
with open(OUTPUT_FILE, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=all_columns, extrasaction="ignore")
    writer.writeheader()
    writer.writerows(rows)

print(f"Converted {len(rows)} events across {len(sessions)} participant(s) → {OUTPUT_FILE}")
